### chat
GET http://localhost:7071/api/chat


### data upload

POST http://localhost:7071/api/data/upload_json
Content-Type: application/json

[
    {
        "id": "3",
        "title": "Azure Cognitive Services",
        "content": "Azure Cognitive Services are a set of AI services that enable you to build intelligent applications with powerful algorithms using just a few lines of code. These services cover a wide range of capabilities, including vision, speech, language, knowledge, and search. They are designed to be easy to use and integrate into your applications. Cognitive Services are fully managed, scalable, and continuously improved by Microsoft. It allows developers to create AI-powered solutions without deep expertise in machine learning.",
        "category": "AI + Machine Learning"
    },
    {
        "id": "4",
        "title": "Azure Storage",
        "content": "Azure Storage is a scalable, durable, and highly available cloud storage service that supports a variety of data types, including blobs, files, queues, and tables. It provides a massively scalable object store for unstructured data. Storage supports data redundancy and geo-replication, ensuring high durability and availability. It offers a variety of data access and management options, including REST APIs, SDKs, and Azure Portal. You can secure your data using encryption at rest and in transit.",
        "category": "Storage"
    }
]